language: node_js

node_js:
   - node # will use latest node

before_install:
    - npm install -g npm
    - npm install -g greenkeeper-lockfile

branches: # branches to watch for changes
  only:
    - master
    - /^greenkeeper/.*$/

cache: # things to cache
  directories:
    - node_modules

before_script: greenkeeper-lockfile-update

script: # the build step
  - npm run build.prod

after_script: greenkeeper-lockfile-upload

deploy: # deploying the application
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change