language: node_js

node_js:
   - node # will use latest node

branches: # branches to watch for changes
  only:
    - master

cache: # things to cache
  directories:
    - node
    - node_modules

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli

script: # the build step
  - npm run build.prod

deploy: # deploying the application
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change